ALTER TABLE student_yurin
ADD Stip_New DECIMAL(8,2);

DELIMITER //
CREATE TRIGGER TR1 BEFORE INSERT 
ON student_yurin FOR EACH ROW
BEGIN
	SET NEW.Stip_New=NEW.Stipendiya*2;
END//
DELIMITER ;

ALTER TABLE student_yurin
ADD PREMIYA DECIMAL(8,2);

UPDATE student_yurin
SET PREMIYA=500

DELIMITER //
CREATE TRIGGER TR2 BEFORE UPDATE 
ON student_yurin FOR EACH ROW
BEGIN
	SET NEW.PREMIYA=NEW.Stipendiya+1000;
END//
DELIMITER ;